<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoCAD.NET" Version="24.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="System.Windows.Forms" />
    </ItemGroup>
</Project>
